name: Build Apptainer Image

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Apptainer
        uses: eWaterCycle/setup-apptainer@v2
        with:
          apptainer-version: 1.4.5

      - name: Build SIF
        run: |
          apptainer build diann.sif .

      - name: Upload Image
        uses: actions/upload-artifact@v4
        with:
          name: diann-sif
          path: diann.sif
          retention-days: 1
